<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Fredericka+the+Great|Mandali&display=swap" rel="stylesheet">
    <style>
        body {
            background: linear-gradient(rgb(255,255,255,.75), rgb(255,255,255,.95)), url(https://cdn.pixabay.com/photo/2017/04/22/00/14/universe-2250310_960_720.jpg);
            width: 100%;
            height: 100vh;
            background-size: cover;
        }
        h1, h2, h3 {
            font-family: 'Fredericka the Great', cursive;
            color: mediumvioletred;
            text-shadow: 1px 2px 3px rgb(0,0,0,.5);
        }
        a, button {
            font-family: 'Fredericka the Great', cursive;
            text-shadow: 1px 2px 3px rgb(0,0,0,.5);
        }
        p, span {
            font-family: 'Mandali', sans-serif;
        }
        .btn-success {
            margin: 2rem 2rem;
            color: #fff;
            background-color: mediumorchid;
            border-color: mediumorchid;
            box-shadow: 1px 2px 3px rgb(0,0,0,.5);

        }
        .btn-success:hover {
            background-color: mediumpurple;
            border-color: mediumpurple;
            position: relative;
            top: -2px;
            box-shadow: 1px 2px 5px rgb(0,0,0,.75);
            transition: .5s;
        }
    </style>
    <title>Home</title>
</head>

<body>
    <main class="home view" style="padding-top: 7rem;">
    <section class="top">
        <div class="container">
            <div class="row flex-column justify-content-center align-content-center">
                <h1 class="text-center">Welcome To Create Profile!</h1><br><br>
                <p>Are you looking for a simple online space to create your own profile?<br> You've come to the right place!</p><br><br>
                
                <a href="/create" class="btn btn-success">Let's Create My Profile</a>
            </div>
        </div>
    </section>
    </main>
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>