<?php  
    $parts = explode('-', $birthday);
    $byear = $parts[0];
    $cyear = date("Y");
    $age = $cyear - $byear;
    
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Fredericka+the+Great|Mandali&display=swap" rel="stylesheet">
    <title>Display Profile</title>
    <style>
        h1, h2, h3 {
            font-family: 'Fredericka the Great', cursive;
            color: mediumvioletred;
            text-shadow: 1px 2px 3px rgb(0,0,0,.5);
        }
        a, button {
            font-family: 'Fredericka the Great', cursive;
            text-shadow: 1px 2px 3px rgb(0,0,0,.5);
        }
        p, span {
            font-family: 'Mandali', sans-serif;
        }
        .details {
            font-family: 'Fredericka the Great', cursive;
            color: mediumvioletred;
            text-shadow: 1px 2px 3px rgb(0,0,0,.5);
        }
       .deets {
            font-size: 1.5rem;
        }
        .tag-tab {
            height: 1rem;
            width: 1.5rem;
            padding: 0.5rem;
            margin: .25rem;
            background-color: #cccccc;
            border-radius: 10px;
            box-shadow: 1px 2px 3px rgb(0,0,0,.5);
            transition: .5s;
            line-height: 4;
        }
        .tag-tab:hover {
            position: relative;
            top: -2px;
            box-shadow: 1px 2px 5px rgb(0,0,0,.75);
            transition: .5s;
        }
        .top {
            padding: 20px;
            background: #00a5;
            padding-bottom: 8rem;
        }
        .btn-success {
            margin: 2rem 2rem;
            color: #fff;
            background-color: mediumorchid;
            border-color: mediumorchid;
            box-shadow: 1px 2px 3px rgb(0,0,0,.5);

        }
        .btn-success:hover {
            background-color: mediumpurple;
            border-color: mediumpurple;
            position: relative;
            top: -2px;
            box-shadow: 1px 2px 5px rgb(0,0,0,.75);
            transition: .5s;
        }
        .cover {
            background: url(https://cdn.pixabay.com/photo/2017/04/22/00/14/universe-2250310_960_720.jpg);
            width: 100%;
            height: 35rem;
            background-size: cover;

        }
        .container {
            background: white;
            margin-top: -17rem;
            padding: 2rem;
            box-shadow: 0px 2px 11px #000;
        }
        .shortbio {
            padding: 2rem 4rem;
        }
        .bdaywish {
            text-align: center;
            padding: 2rem;
            border: 5px solid mediumvioletred;
            margin: 1rem;
            box-shadow: 0px 4px 5px #ccc;
            background-color: black;
        }
    </style>
</head>
<body>
    <main class="submit view">
        <section class="cover">

        </section>
        <section class="top">
            <div class="container">
            
                <h1 class="text-center"><?= $fname ?>'s Profile</h1>
                <div class="row flex-column justify-content-center align-content-center">
                   <!-- <div class="col-lg-5">
                        <div class="picbox">
                            <//?= $picture ?>
                        </div>
                    </div>-->
                    <div class="col-lg-12" style="padding-left: 5rem;">
                        <div class="name">
                             <p class="deets"><span class="details">Full Name:</span>&nbsp;<?= $fname ?>&nbsp;<?= $lname ?></p>
                        </div>
                        <div class="birthday">
                            <?php $bday = new DateTime($birthday)?>
                             <p class="deets"><span class="details">Birthday:</span>&nbsp; <?= date_format($bday, "M d, Y") ?></p>
                        </div>
                        <div class="age">
                        <p class="deets"> <span class="details">Age:</span>&nbsp; <?= $age ?></p>
                        </div>
                    </div>
                </div>
                <div class="row justify-content-center align-content-center">
                    <div class="col-lg-9" style="border-right: 2px solid darkgray;">
                        <div class="shortbio">
                            <h3><?= $fname ?>'s Bio</h3>
                            <p><?= $shortbio ?></p>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="interests">
                            <?php  $all_interests = explode(',', $interests);
                            foreach($all_interests as $interest) { ?>
                              <span class="tag-tab"> <?= $interest ?> </span>
                                <?php } ?>
                           
                        </div>
                        <?php 
                        $currdate = date("m-d");
                        $yourbday = date_format($bday, "m-d");
                           if ($yourbday == $currdate) {
                               echo '<h3 class="bdaywish">Happy Birthday!</h3>';
                           }
                           //var_dump($currdate);
                           //var_dump($yourbday);
                        ?>
                        </div>
                       
                </div>
                <a href="/create" class="btn btn-success"> Re-do Your Profile</a>
                <a href="/home" class="btn btn-success">Go Back Home</a>
            </div>
        </section>
    </main>
    
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>